import DOMPurify from "isomorphic-dompurify";

/** Tags nécessaires aux templates PDF Handlebars (pas de scripts / iframes). */
const PDF_ALLOWED_TAGS = [
  "html",
  "head",
  "meta",
  "title",
  "style",
  "body",
  "div",
  "p",
  "span",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "table",
  "thead",
  "tbody",
  "tr",
  "th",
  "td",
  "strong",
  "em",
  "b",
  "i",
  "u",
  "br",
  "hr",
  "section",
  "article",
  "header",
  "footer",
  "small",
  "blockquote",
  "dl",
  "dt",
  "dd",
  "colgroup",
  "col",
] as const;

const PDF_ALLOWED_ATTR = [
  "class",
  "style",
  "id",
  "lang",
  "charset",
  "name",
  "content",
  "colspan",
  "rowspan",
  "align",
  "valign",
  "width",
  "height",
  "border",
  "cellpadding",
  "cellspacing",
] as const;

/**
 * Dernière barrière avant Puppeteer : supprime scripts, handlers inline,
 * iframes et liens javascript: même si une faille Handlebars passait.
 */
export function sanitizePdfHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [...PDF_ALLOWED_TAGS],
    ALLOWED_ATTR: [...PDF_ALLOWED_ATTR],
    ALLOW_DATA_ATTR: false,
    FORBID_TAGS: [
      "script",
      "iframe",
      "frame",
      "frameset",
      "object",
      "embed",
      "applet",
      "link",
      "base",
      "form",
      "input",
      "button",
      "textarea",
      "select",
      "option",
    ],
    FORBID_ATTR: [
      "onerror",
      "onload",
      "onclick",
      "onmouseover",
      "onfocus",
      "onblur",
      "onchange",
      "onsubmit",
    ],
    ALLOW_UNKNOWN_PROTOCOLS: false,
    SAFE_FOR_TEMPLATES: true,
  });
}
